name: Deploy to GitHub Pages

on:
  # Roda esse workflow toda vez que algo é subido (push) na branch principal (main ou master)
  push:
    branches:
      - main
      - master
  
  # Permite que você rode essa action manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy simultâneo, pulando filas
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de construção (Build)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # A pasta "dist" é gerada pelo comando de build do Vite
          path: './dist'

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
